name: ffmpeg_converter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  creator: ^0.3.1
  ffi: ^2.0.1
  path_provider: ^2.0.14
  flutter:
    sdk: flutter
  file_picker: ^5.2.11
  
  
  
  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
