name: ffmpeg_converter
description: A media conversion tool currently for Windows that allows changing media type and compression size using ffmpeg backend.
publish_to: 'none'
version: 0.1.3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ffi: ^2.0.1
  file_picker: ^6.1.1
  flutter:
    sdk: flutter  
  flutter_riverpod: ^2.4.2
  path_provider: ^2.0.14
  riverpod: ^2.4.1
  
  
flutter_launcher_icons:
  image_path: assets/verticrow2.ico
  windows:
    generate: true
    image_path: assets/verticrow2.ico
    icon_size: 48
  
  
  
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/globe.jpg
    - assets/verticrow2.ico